### ISSUE TITLE
[Feature request] Auto Updater

### ISSUE THREAD

**Issue by ScarVite** [Kxnrl/GenshinDiscordRpc#6]
This could be Achieved by comparing the local version to a version stored on a server f.e. in the json format and if the server version is newer, it could automatically download and install the new update.
Squirrel should be able to help you with installing.
I can provide logical support, as i already coded multiple updaters in js, but im not good in c#, so i can't help you coding it

**Comment by Kxnrl** [comment]
I don't think it's necessary.
